# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "test"
client_id = "b2c2a60b60c2f5458a1446412d7d52c5"
application_url = "https://prominent-stood-liberia-order.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://prominent-stood-liberia-order.trycloudflare.com/auth/callback",
  "https://prominent-stood-liberia-order.trycloudflare.com/auth/shopify/callback",
  "https://prominent-stood-liberia-order.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "pos-add-product.myshopify.com"
