# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "product-add-3"
client_id = "d0c59ec45ce3ec5f19349e3d257105c8"
application_url = "https://tribunal-errors-worked-minolta.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://tribunal-errors-worked-minolta.trycloudflare.com/auth/callback",
  "https://tribunal-errors-worked-minolta.trycloudflare.com/auth/shopify/callback",
  "https://tribunal-errors-worked-minolta.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "pos-add-product.myshopify.com"
