# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "product-add-test"
client_id = "4c87882b2081d74a105a6ea448dc4911"
application_url = "https://guys-entire-originally-probe.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://guys-entire-originally-probe.trycloudflare.com/auth/callback",
  "https://guys-entire-originally-probe.trycloudflare.com/auth/shopify/callback",
  "https://guys-entire-originally-probe.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "pos-add-product.myshopify.com"
